#!/bin/sh
#----- On version change:
#-----    Update version in .profile_spi and check ssm dependenciesw

arg=$1

NAME="SPI"
DESCRIPTION="Meteorological GIS, Processing and Modeling tool"
SUMMARY="4D virtual globe for scientific visualisation and analytics"
VERSION="8.0.0"
MAINTAINER="Jean-Philippe Gauthier"
BUILDINFO=`git describe --always`


SSM_NAME=${NAME}_${VERSION}_all

echo ""
echo "----- Building platform : ${ORDENV_PLAT} -----"
echo ""

if [[ $arg = "-ssm" ]]; then

   echo ""
   echo "----- Building ssm package : ${SSM_DEV}/workspace/${SSM_NAME} ----- "
   echo ""

   rm -f -r ${SSM_DEV}/workspace/${SSM_NAME} ${SSM_DEV}/package/${SSM_NAME}.ssm 
   mkdir -p ${SSM_DEV}/workspace/${SSM_NAME}/.ssm.d ${SSM_DEV}/workspace/${SSM_NAME}/etc/profile.d ${SSM_DEV}/workspace/${SSM_NAME}/lib
   cp -r  bin tcl share data/ .profile_spi tclsh tclshd wish ${SSM_DEV}/workspace/${SSM_NAME}
   cp .ssm.d/post-install ${SSM_DEV}/workspace/${SSM_NAME}/.ssm.d
   find ${SSM_DEV}/workspace/${SSM_NAME} -name .svn -prune -exec rm -f -r {} \;
   find ${SSM_DEV}/workspace/${SSM_NAME} \( -name "*~" -o -name ".*.sw?" -o -name ".nfs*" \) -delete
   sed -e "s/NAME/${NAME}/" -e "s/VERSION/${VERSION}/" -e "s/PLATFORM/all/" -e "s/MAINTAINER/${MAINTAINER}/" -e "s/BUILDINFO/${BUILDINFO}/" -e "s/DESCRIPTION/${DESCRIPTION}/" -e "s/SUMMARY/${SUMMARY}/".ssm.d/control.json > ${SSM_DEV}/workspace/${SSM_NAME}/.ssm.d/control.json
   cd ${SSM_DEV}/workspace; tar -zcvf ${SSM_DEV}/package/${SSM_NAME}.ssm ${SSM_NAME}
   rm -f -r ${SSM_DEV}/workspace/${SSM_NAME}   
fi
