#!/bin/ksh

export SPI_PATH=${0%tclsh}
. ${SPI_PATH}/.profile_spi

#----- Force  software GL, usefull for tclsh only script
export LD_LIBRARY_PATH=${SPI_SHARED}/GL:$LD_LIBRARY_PATH

${SPI_SHARED}/TclTk/bin/tclsh${TCL_VERSION} "$@"