#!/bin/ksh

export SPI_PATH=${0%wish}
. ${SPI_PATH}/.profile_spi

#----- Force  software GL, usefull for tclsh only script
export LD_LIBRARY_PATH=${SPI_LIB}/GL:$LD_LIBRARY_PATH

#----- One can use SPI_DEBUG="valgrind --track-origins=yes --leak-check=full" to debug memory problems
exec ${SPI_DEBUG} ${SPI_LIB}/TCL/bin/wish${TCL_VERSION} "$@"

