#!/bin/sh

MAKE=make

echo ""
echo "----- Architecture Found :  ${BASE_ARCH} -----"
echo ""

echo ""
echo "----- Cleaning System Call Library Object -----"
echo ""
cd TclSystem
$MAKE distclean

echo ""
echo "----- Cleaning OpenGL Renderer Library Object -----"
echo ""
cd ../TkglCanvas
$MAKE distclean

echo ""
echo "----- Cleaning Tcl GeoEER Library Object -----"
echo ""
cd ../TclGeoEER
$MAKE distclean
