#!/bin/sh

ARCH=`uname -s`
MAKE=make

echo ""
echo "----- Architecture Found : $ARCH -----"
echo ""

echo ""
echo "----- Cleaning System Call Library  Object -----"
echo ""
cd TclSystem
$MAKE clean

echo ""
echo "----- Cleaning OpenGL Renderer Library  Object -----"
echo ""
cd ../TkglCanvas
$MAKE clean

echo ""
echo "----- Cleaning EER Data Library Object -----"
echo ""
cd ../TclData
$MAKE clean

echo ""
echo "----- MCleaning Tk Viewport Library Object -----"
echo ""
cd ../TkViewport
$MAKE clean
