#!/bin/sh
#----- On version change:
#-----    Update version in .profile_spi
#-----    Change version in TclGeoEER/configure.in
#-----    Change version in TclTk/lib/tclConfig.sh and tkConfig.sh for all platform
#-----    Change version in gdal.../bin/gdal-config for all platform
#-----    ./makeit reconf
#-----    Make sure BUFR dictionnaries and RPN dictionnaries are up-to-date

arg=$1

NAME="SPI"
DESC="EER Visualisation, GIS, Processing and Modeling tool"
VERSION="7.7.1"
MAINTAINER="Jean-Philippe Gauthier"

SSM_NAME=${NAME}_${VERSION}_multi

MAKE=make
LIB=/users/dor/afsr/005/Links/dev/Lib/${VERSION}/${ORDENV_PLAT}
TCL=${LIB}/SPI

export CC=c99
export CFLAGS=-fopenmp
#export CFLAGS=" -fopenmp -lmkl_intel_lp64 -lmkl_core -lmkl_intel_lp64 -lmkl_core -lmkl_intel_thread -liomp5 -lpthread -lm"

echo ""
echo "----- Building platform : ${ORDENV_PLAT} -----"
echo ""

if [[ $arg = "ssm" ]]; then

   echo ""
   echo "----- Building ssm package : ${SSM_DEV}/workspace/${SSM_NAME} ----- "
   echo ""

   cd ../eer_SPI
   rm -f -r ${SSM_DEV}/workspace/${SSM_NAME} ${SSM_DEV}/package/${SSM_NAME}.ssm 
   mkdir -p ${SSM_DEV}/workspace/${SSM_NAME}/.ssm.d ${SSM_DEV}/workspace/${SSM_NAME}/etc/profile.d ${SSM_DEV}/workspace/${SSM_NAME}/lib
   cp -r  bin    ${SSM_DEV}/workspace/${SSM_NAME}
   for plat in `ls -1 lib`; do
      cp -r  lib/${plat}/ ${SSM_DEV}/workspace/${SSM_NAME}/lib
   done
   cp -r  tcl    ${SSM_DEV}/workspace/${SSM_NAME}
   cp -r  share  ${SSM_DEV}/workspace/${SSM_NAME}
   cp -r  data   ${SSM_DEV}/workspace/${SSM_NAME}
   cp .profile_spi tclsh tclshd wish ${SSM_DEV}/workspace/${SSM_NAME}
   cp .ssm.d/post-install ${SSM_DEV}/workspace/${SSM_NAME}/.ssm.d
   find ${SSM_DEV}/workspace/${SSM_NAME} -name .svn -exec rm -f -r {} \;
   find ${SSM_DEV}/workspace/${SSM_NAME} -name *~ -delete
   find ${SSM_DEV}/workspace/${SSM_NAME} -name .nfs* -delete
   sed -e "s/NAME/${NAME}/" -e "s/VERSION/${VERSION}/" -e "s/PLATFORM/all/" -e "s/MAINTAINER/${MAINTAINER}/" -e "s/DESC/${DESC}/" .ssm.d/control > ${SSM_DEV}/workspace/${SSM_NAME}/.ssm.d/control
   cd ${SSM_DEV}/workspace/${SSM_NAME}/lib; ln -s ubuntu-10.04-amd64-64 Linux_x86_64; cd -
   cd ${SSM_DEV}/workspace; tar -zcvf ${SSM_DEV}/package/${SSM_NAME}.ssm ${SSM_NAME}
   
   
elif [[ $arg = "src" ]]; then

   ./cleanit
   rm -f -r ${SSM_DEV}/workspace/LibTkGL
   cp -r ../LibTkGL ${SSM_DEV}/workspace
   find ${SSM_DEV}/workspace/LibTkGL -name .svn -exec rm -f -r {} \;
   find ${SSM_DEV}/workspace/LibTkGL -name *~ -delete
   cd ${SSM_DEV}/workspace; tar -zcvf ${SSM_DEV}/package/libSPI-${VERSION}_src.tgz LibTkGL
   
else

  echo ""
  echo "----- Making System Call Library Object -----"
  echo ""
  cd TclSystem
  if [[ $arg = "reconf" ]]; then
     make distclean
     autoconf2.50
     ./configure \
	--exec-prefix=${TCL}/TclTk \
	--enable-threads \
	--enable-64bit \
	--with-tcl=${TCL}/TclTk/lib \
	--with-eer=${SSM_DEV}/workspace/eerUtils_1.8.0_${ORDENV_PLAT}
  #      --with-dmv=/home/ordenv/ssm-domains/ssm-utils/dmv_1.0_linux26-x86-64
  fi

  $MAKE install

  echo ""
  echo "----- Making OpenGL Canvas Library Object -----"
  echo ""

  cd ../TkglCanvas
  if [[ $arg = "reconf" ]]; then
     make distclean
     autoconf2.50
     ./configure \
	--prefix=${TCL}/TclTk/ \
	--exec-prefix=${TCL}/TclTk/ \
	--enable-threads \
	--enable-64bit \
	--with-tcl=${TCL}/TclTk/lib \
	--with-tk=${TCL}/TclTk/lib
  fi

  $MAKE install

  echo ""
  echo "----- Making Tcl GeoEER Library Object -----"
  echo ""

  cd ../TclGeoEER
  if [[ $arg = "reconf" ]]; then
      make distclean
      autoconf2.50
      ./configure \
	--exec-prefix=${TCL}/TclTk \
	--enable-threads \
	--enable-64bit \
	--with-tcl=${TCL}/TclTk/lib \
	--with-tk=${TCL}/TclTk/lib \
	--with-eer=${SSM_DEV}/workspace/eerUtils_1.8.0_${ORDENV_PLAT}\
	--with-rmn=${LIB}/librmn-14 \
	--with-gdb=${LIB}/gdb \
	--with-gdal=${LIB}/gdal-1.11.0/bin/gdal-config  \
	--with-grib=${LIB}/grib_api-1.12.0 \
	--with-ecbufr=${LIB}/libecbufr-0.8.2rc1 \
	--with-flt=${LIB}/fltlib-0.5.1 \
        --with-urp=${LIB}/URP
  fi

  $MAKE install

  cd ${TCL}
  ln -fs TclTk/lib/TclGeoEER${VERSION}/libTclGeoEER${VERSION}.so libTclGeoEER${VERSION}.so
  ln -fs libTclGeoEER${VERSION}.so libTclGeoEER.so

  ln -fs TclTk/lib/TkglCanvas8.6/libTkglCanvas8.6.so libTkglCanvas8.6.so
  ln -fs libTkglCanvas8.6.so libTkglCanvas.so

  ln -fs TclTk/lib/TclSystem1.1/libTclSystem1.0.so libTclSystem1.1.so
  ln -fs libTclSystem1.1.so libTclSystem.so

fi
