#!/bin/bash
# If changing this file, relfect the changes in libSPI.sh
# post-install <domainHome> <packageHome>

domainHome=$1
packageHome=$2

# create profiles
packageName=`basename ${packageHome}`
profileDirPath=${packageHome}/etc/profile.d
profilePath=${profileDirPath}/${packageName}.sh
loginPath=${profileDirPath}/${packageName}.csh

rm -f ${profilePath} ${loginPath}
mkdir -p ${profileDirPath}

cat > ${profilePath} << EOF

export SPI_LIB="${packageHome}"
export EC_INCLUDE_PATH="${packageHome}/include \${EC_INCLUDE_PATH}"
export EC_LD_LIBRARY_PATH="${packageHome}/lib \${EC_LD_LIBRARY_PATH}"

#----- GDAL data
export GDAL_PAM_ENABLED=NO
export CPL_LOG=/dev/null

#type sscp >/dev/null 2>&1 || . ssmuse-sh -d hpcs/ext/sscp

if [ `domainname -d` = "science.gc.ca" ]; then
   #----- On the SCIENCE side
   if [ -z "\${ECCODES_DEFINITION_PATH}" ];then 
      . ssmuse-sh -x /fs/ssm/eccc/cmd/cmds/extsup/shared/20181017
   fi
   if [ ! -d "\${GDB_PATH}" ]; then
      export GDB_PATH=/home/ords/cmod/cmoe/ops/smco600/geo/DBGeo/data
   fi
else 
   #----- On the EC side
   if [ -z "\${ECCODES_DEFINITION_PATH}" ];then 
      . ssmuse-sh -x /ssm/net/cmds/extsup/shared/20181017
   fi
   if [ ! -d "\${GDB_PATH}" ]; then
      export GDB_PATH=/cnfs/ops/production/cmoe/geo/DBGeo/data
   fi

#----- GDB data
if [ ! -d "\${GDB_PATH}" ]; then
   if [ `domainname -d` = "science.gc.ca" ]; then
      #----- On the SCIENCE side
      export GDB_PATH=/home/ords/cmod/cmoe/ops/smco600/geo/DBGeo/data
   else
      #----- On the EC side
      export GDB_PATH=/cnfs/ops/production/cmoe/geo/DBGeo/data
   fi
fi

#----- Force BURP table dir since it's hardcoded with RMN and problem outside cmc
if [ -z \${AFSISIO} ]; then
   export MA_TABLEBURP_PERSONNELLE=\${SPI_LIB}/share/rmn/table_b_bufr
fi
EOF

cat > ${loginPath} << EOF
setenv SPI_LIB="${packageHome}"
setenv EC_INCLUDE_PATH="${packageHome}/include \${EC_INCLUDE_PATH}"
setenv EC_LD_LIBRARY_PATH="${packageHome}/lib \${EC_LD_LIBRARY_PATH}"

#----- GDAL data
setenv GDAL_PAM_ENABLED=NO
setenv CPL_LOG=/dev/null

#----- GDB data
if [ -z \${GDB_PATH} ]; then
   if [ `domainname -d` = "science.gc.ca" ]; then
      #----- On the SCIENCE side
      setenv GDB_PATH=/home/ords/cmod/cmoe/ops/smco600/geo/DBGeo/data
   else
      #----- On the EC side
      setenv GDB_PATH=/cnfs/ops/production/cmoe/geo/DBGeo/data
   fi
fi

#----- Force BURP table dir since it's hardcoded with RMN and problem outside cmc
if [ -z \${AFSISIO} ]; then
   setenv MA_TABLEBURP_PERSONNELLE=\${SPI_LIB}/share/rmn/table_b_bufr
fi
EOF
