#!/bin/bash
# If changing this file, relfect the changes in libSPI.sh
# post-install <domainHome> <packageHome>

domainHome=$1
packageHome=$2

# create profiles
packageName=`basename ${packageHome}`
profileDirPath=${packageHome}/etc/profile.d
profilePath=${profileDirPath}/${packageName}.sh
loginPath=${profileDirPath}/${packageName}.csh

rm -f ${profilePath} ${loginPath}
mkdir -p ${profileDirPath}

cat > ${profilePath} << EOF
export SPI_LIB="${packageHome}"
export EC_INCLUDE_PATH="${packageHome}/include \${EC_INCLUDE_PATH}"
export EC_LD_LIBRARY_PATH="${packageHome}/lib \${EC_LD_LIBRARY_PATH}"

#----- GDAL data
export GDAL_DATA=\${SPI_LIB}/share/gdal
export GDAL_PAM_ENABLED=NO
export CPL_LOG=/dev/null

#----- PROJ4 data
export PROJ_LIB=\${SPI_LIB}/share/proj

#----- Force GRIB API Tables
export GRIB_SAMPLES_PATH=\${SPI_LIB}/share/grib_api/samples
export GRIB_DEFINITION_PATH=\${SPI_LIB}/share/grib_api/definitions

#----- GDB data
if [ ! -d "\${GDB_PATH}" ]; then
   if [ `domainname -d` = "science.gc.ca" ]; then
      #----- On the SCIENCE side
      export GDB_PATH=/home/ords/cmod/cmoe/ops/smco600/geo/DBGeo/data
   else
      #----- On the EC side
      export GDB_PATH=/cnfs/ops/production/cmoe/geo/DBGeo/data
   fi
fi

#----- Force BURP table dir since it's hardcoded with RMN and problem outside cmc
if [ -z \${AFSISIO} ]; then
   export MA_TABLEBURP_PERSONNELLE=\${SPI_LIB}/share/rmn/table_b_bufr
fi
EOF

cat > ${loginPath} << EOF
setenv SPI_LIB="${packageHome}"
setenv EC_INCLUDE_PATH="${packageHome}/include \${EC_INCLUDE_PATH}"
setenv EC_LD_LIBRARY_PATH="${packageHome}/lib \${EC_LD_LIBRARY_PATH}"

#----- GDAL data
setenv GDAL_DATA=\${SPI_LIB}/share/gdal
setenv GDAL_PAM_ENABLED=NO
setenv CPL_LOG=/dev/null

#----- PROJ4 data
setenv PROJ_LIB=\${SPI_LIB}/share/proj

#----- Force GRIB API Tables
setenv GRIB_SAMPLES_PATH=\${SPI_LIB}/share/grib_api/samples
setenv GRIB_DEFINITION_PATH=\${SPI_LIB}/share/grib_api/definitions

#----- GDB data
if [ -z \${GDB_PATH} ]; then
   if [ `domainname -d` = "science.gc.ca" ]; then
      #----- On the SCIENCE side
      setenv GDB_PATH=/home/ords/cmod/cmoe/ops/smco600/geo/DBGeo/data
   else
      #----- On the EC side
      setenv GDB_PATH=/cnfs/ops/production/cmoe/geo/DBGeo/data
   fi
fi

#----- Force BURP table dir since it's hardcoded with RMN and problem outside cmc
if [ -z \${AFSISIO} ]; then
   setenv MA_TABLEBURP_PERSONNELLE=\${SPI_LIB}/share/rmn/table_b_bufr
fi
EOF
