#!/bin/bash
# If changing this file, relfect the changes in libSPI.sh
# post-install <domainHome> <packageHome>

domainHome=$1
packageHome=$2

# create profiles
packageName=`basename ${packageHome}`
profileDirPath=${packageHome}/etc/profile.d
profilePath=${profileDirPath}/${packageName}.sh
loginPath=${profileDirPath}/${packageName}.csh

rm -f ${profilePath} ${loginPath}
mkdir -p ${profileDirPath}

cat > ${profilePath} << EOF

export SPI_LIB="${packageHome}"
export EC_INCLUDE_PATH="${packageHome}/include \${EC_INCLUDE_PATH}"
export EC_LD_LIBRARY_PATH="${packageHome}/lib \${EC_LD_LIBRARY_PATH}"

#----- GDAL data
export GDAL_PAM_ENABLED=NO
export CPL_LOG=/dev/null

#----- Dependencies
if [ `domainname -d` = "science.gc.ca" ]; then

   #----- On the SCIENCE side
   [[ "\${LD_LIBRARY_PATH}" =~ .*intelcomp.* ]] || . ssmuse-sh -x main/opt/intelcomp/intelcomp-2016.1.156 -x main/opt/openmpi/openmpi-1.6.5/intelcomp-2016.1.156
   [ -n "\${ECCODES_DEFINITION_PATH}" ]         || . ssmuse-sh -d eccc/cmd/cmds/extsup/shared/master
   [ -d "\${GDB_PATH}" ]                        || export GDB_PATH=/home/ords/cmod/cmoe/ops/smco600/geo/DBGeo/data
else 
   #----- On the EC side
   [ -n "\${ECCODES_DEFINITION_PATH}" ] || . ssmuse-sh -d cmds/ext/20190205
   [ -d "\${GDB_PATH}" ]                || export GDB_PATH=/home/binops/afse/eer/links/geo/DBGeo/data
fi

EOF

cat > ${loginPath} << EOF
setenv SPI_LIB="${packageHome}"
setenv EC_INCLUDE_PATH="${packageHome}/include \${EC_INCLUDE_PATH}"
setenv EC_LD_LIBRARY_PATH="${packageHome}/lib \${EC_LD_LIBRARY_PATH}"

#----- GDAL data
setenv GDAL_PAM_ENABLED=NO
setenv CPL_LOG=/dev/null

if [ `domainname -d` = "science.gc.ca" ]; then
   #----- On the SCIENCE side
   [[ "\${LD_LIBRARY_PATH}" =~ .*intelcomp.* ]] || . ssmuse-sh -d main/opt/intelcomp/intelcomp-2016.1.156 -d main/opt/openmpi/openmpi-1.6.5/intelcomp-2016.1.156
   [ -n "\${ECCODES_DEFINITION_PATH}" ] || . ssmuse-sh -d eccc/cmd/cmds/extsup/shared/master
   [ -d "\${GDB_PATH}" ]                || setenv GDB_PATH=/home/ords/cmod/cmoe/ops/smco600/geo/DBGeo/data
else 
   #----- On the EC side
   [ -n "\${ECCODES_DEFINITION_PATH}" ] || . ssmuse-sh -d cmds/ext/20190205
   [ -d "\${GDB_PATH}" ]                || setenv GDB_PATH=/home/binops/afse/eer/links/geo/DBGeo/data
fi

EOF
