#!/bin/bash
#
# post-install <domainHome> <packageHome>

domainHome=$1
packageHome=$2

# create profiles
packageName=`basename ${packageHome}`
packageVersion=`echo $packageName | cut -d _ -f2`
profileDirPath=${packageHome}/etc/profile.d
profilePath=${profileDirPath}/${packageName}.sh
loginPath=${profileDirPath}/${packageName}.csh

rm -f ${profilePath} ${loginPath}
mkdir -p ${profileDirPath}

cat > ${profilePath} << EOF
export SPI_PATH=${packageHome}

#----- If within CMC environment and SPI_LIB not loaded, load only the profile
[[ -n \${ORDENV_VERSION} && -z \${SPI_LIB} && -d ${domainHome}/libSPI_${packageVersion}_\${ORDENV_PLAT} ]] && . ${domainHome}/libSPI_${packageVersion}_\${ORDENV_PLAT}/etc/profile.d/libSPI_${packageVersion}_\${ORDENV_PLAT}.sh || exit
EOF
